# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins:
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  NewCops: enable

# RSpec settings
RSpec/MultipleExpectations:
  Max: 3
  Exclude:
    - 'spec/system/**/*'

RSpec/ExampleLength:
  Max: 10
  Exclude:
    - 'spec/system/**/*'
